### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by pangrr** [YuPototo/jp_conjugation#1]
**General Good Practices**
- Best to have typescript interface for state. If not, better to put sample data, as a proxy to state interface, in the same file as state.
- Name variables/functions so that the purposes are immediately understood. General words like 'Content' is usually a sign for improvement. e.g.
     - `state.contents` vs. `state.cardGroups`
     - `getters.getTitle` vs. `getCardGroupTitle`
- `getters.getContents` is unnecessary because for the only user `TableContent.vue` you can use `state.contents` and display `id` and `title` of each part while ignoring the `cards`. In a word 'selective display'.
- Always use single quotes or always use double quotes. Don't mix.
- Use `===` instead of `==` whenever possible.

**App Specifics**
- Why not get whole `part` data in `Exercise.vue` and pass whole `card` data to `ExerciseCard.vue`?
- Remove unused `class` attributes. e.g. `class='list-group list-group-flush'`.
- `ExerciseCard.vue` line 40 should be deleted. And the `computed` can be simplified use `mapGetters`.
- Component name in `Exercise.vue` is wrong.

**Comment by YuPototo** [comment]
太棒了！！

**Comment by YuPototo** [comment]
> Best to have typescript interface for state. If not, better to put sample data, as a proxy to state interface, in the same file as state.
sample data 在 `src/data/data.js` 里，这样可以吗。

> Name variables/functions so that the purposes are immediately understood. 
好的！起名字确实是个痛苦的事儿啊。

> getters.getContents is unnecessary 
按照这个建议修改啦。

> Always use single quotes or always use double quotes. Don't mix.
这个碰到就改。一般优先用哪个呢？

> Use === instead of == whenever possible.
Yes!

---

> Why not get whole part data in `Exercise.vue` and pass whole card data to `ExerciseCard.vue`?
这个电话聊下哈。

> Remove unused class attributes. e.g. class='list-group list-group-flush'.
这是 bootstrap 的 class。

> `ExerciseCard.vue` line 40 should be deleted. 
删掉之后不知道怎么实现我想要的功能了。具体电话聊哈。

> And the computed can be simplified use mapGetters.
改了！这个思路确实更好。不过我有点搞混了，什么时候该用 Getter 呢？
